----------------------- 에그마요
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 1);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 15);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 1, 22);

----------------------- 로스트치킨
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 12);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 16);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 2, 24);

----------------------- 쉬림프
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 2);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 13);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 17);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 21);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 3, 22);

----------------------- 스테이크치즈
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 9);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 12);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 18);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 22);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 4, 24);

----------------------- 베지
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 2);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 22);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 5, 24);

----------------------- 베지아보카도
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 2);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 10);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 22);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 6, 24);

----------------------- 로스트치킨아보카도
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 10);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 12);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 16);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 7, 24);

----------------------- 비엘티
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 1);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 13);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 8, 23);

----------------------- 풀드포크
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 9);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 12);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 14);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 21);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 9, 24);

----------------------- 치킨데리야끼
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 1);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 13);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 16);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 10, 24);

----------------------- 터키베이컨아보카도
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 2);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 10);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 16);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 22);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 11, 24);

----------------------- 로티세리
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 13);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 16);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 18);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 20);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 12, 24);

----------------------- 비엠티
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 1);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 14);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 21);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 13, 24);

----------------------- K-바비큐
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 3);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 9);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 13);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 18);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 21);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 14, 23);

----------------------- 스파이시이탈리안
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 2);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 4);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 5);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 6);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 7);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 8);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 9);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 11);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 14);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 19);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 21);
INSERT INTO COMBINATION VALUES(SEQ_COMNO.NEXTVAL, 15, 23);

COMMIT;