INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, 'admin', '서울특별시', '111@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'A');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김말똥', '강서구', '222@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '박말순', '강남구', '333@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '박금자', '종로구', '444@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김윤성', '중구', '555@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이승재', '용산구', '666@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '최현식', '성동구', '777@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '남기윤', '광진구', '888@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '최민석', '동대문구', '999@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이영운', '중랑구', '1110@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이종민', '성북구', '1221@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '정종훈', '강북구', '1332@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김병준', '도봉구', '1443@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '오승준', '노원구', '1554@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '최건호', '은평구', '1665@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '최유림', '서대문구', '1776@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이성호', '마포구', '1887@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '백승한', '양천구', '1998@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김성록', '강서구', '2109@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김병선', '구로구', '2220@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '유상종', '금천구', '2331@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김동민', '영등포구', '2442@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '권순창', '동작구', '2553@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '황현수', '관악구', '2664@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이승민', '서초구', '2775@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '유재현', '강남구', '2886@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '송영준', '송파구', '2997@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '이선학', '강동구', '3108@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '송민근', '강서구', '3219@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '강풍윤', '마포구', '3330@gmail.com', '010-0000-0000', 'sand5rang', 'sand5rang', 'Y');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '강영우', '강서구', '33230@gmail.com', '010-0000-0000', 'sand5rang에 가입하고싶습니다!', '일정 맞춰주세요!', 'B');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '유동연', '강남구', '33330@gmail.com', '010-0000-0000', '가맹신청합니다!!', '일정 맞춰서 조율해주세요!', 'B');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김우재', '강동구', '3415330@gmail.com', '010-0000-0000', '샌드오랑 가맹문의합니다.', '일정 맞춰서 조율해주세요!', 'B');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '김주형', '강북구', '331130@gmail.com', '010-0000-0000', '5rang에 가입하고 싶습니다!!!', '일정 맞춰서 조율해주세요!', 'B');

INSERT INTO ENROLL (ENR_NO, STORE_NAME, ENROLL_ADD, EMAIL, PHONE, TITLE, CONTENT, STATUS) 
VALUES (SEQ_ENRNO.NEXTVAL, '송가원', '종로구', '3322330@gmail.com', '010-0000-0000', '문의드릴 사항이 있습니다.', '일정 맞춰서 조율해주세요!', 'B');

