
INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220701', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220701', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220701', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220701', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220701', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220701', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220701', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220701', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220701', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220701', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220701', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220701', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220701', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220701', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220701', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220701', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220701', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220701', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220701', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220701', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220701', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220701', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220701', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220701', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220702', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220702', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220702', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220702', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220702', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220702', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220702', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220702', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220702', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220702', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220702', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220702', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220702', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220702', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220702', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220702', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220702', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220702', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220702', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220702', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220702', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220702', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220702', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220702', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220703', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220703', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220703', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220703', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220703', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220703', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220703', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220703', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220703', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220703', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220703', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220703', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220703', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220703', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220703', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220703', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220703', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220703', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220703', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220703', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220703', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220703', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220703', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220703', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220704', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220704', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220704', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220704', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220704', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220704', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220704', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220704', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220704', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220704', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220704', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220704', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220704', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220704', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220704', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220704', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220704', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220704', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220704', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220704', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220704', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220704', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220704', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220704', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220705', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220705', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220705', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220705', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220705', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220705', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220705', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220705', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220705', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220705', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220705', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220705', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220705', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220705', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220705', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220705', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220705', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220705', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220705', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220705', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220705', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220705', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220705', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220705', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220706', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220706', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220706', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220706', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220706', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220706', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220706', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220706', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220706', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220706', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220706', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220706', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220706', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220706', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220706', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220706', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220706', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220706', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220706', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220706', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220706', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220706', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220706', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220706', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220707', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220707', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220707', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220707', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220707', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220707', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220707', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220707', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220707', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220707', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220707', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220707', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220707', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220707', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220707', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220707', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220707', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220707', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220707', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220707', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220707', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220707', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220707', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220707', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220708', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220708', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220708', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220708', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220708', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220708', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220708', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220708', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220708', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220708', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220708', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220708', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220708', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220708', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220708', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220708', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220708', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220708', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220708', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220708', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220708', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220708', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220708', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220708', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220709', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220709', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220709', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220709', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220709', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220709', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220709', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220709', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220709', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220709', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220709', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220709', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220709', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220709', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220709', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220709', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220709', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220709', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220709', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220709', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220709', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220709', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220709', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220709', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220710', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220710', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220710', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220710', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220710', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220710', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220710', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220710', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220710', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220710', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220710', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220710', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220710', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220710', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220710', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220710', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220710', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220710', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220710', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220710', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220710', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220710', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220710', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220710', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220711', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220711', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220711', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220711', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220711', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220711', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220711', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220711', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220711', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220711', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220711', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220711', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220711', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220711', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220711', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220711', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220711', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220711', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220711', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220711', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220711', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220711', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220711', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220711', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220712', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220712', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220712', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220712', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220712', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220712', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220712', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220712', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220712', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220712', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220712', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220712', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220712', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220712', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220712', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220712', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220712', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220712', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220712', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220712', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220712', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220712', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220712', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220712', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220713', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220713', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220713', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220713', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220713', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220713', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220713', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220713', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220713', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220713', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220713', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220713', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220713', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220713', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220713', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220713', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220713', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220713', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220713', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220713', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220713', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220713', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220713', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220713', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220714', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220714', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220714', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220714', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220714', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220714', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220714', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220714', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220714', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220714', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220714', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220714', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220714', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220714', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220714', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220714', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220714', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220714', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220714', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220714', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220714', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220714', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220714', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220714', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220715', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220715', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220715', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220715', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220715', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220715', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220715', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220715', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220715', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220715', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220715', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220715', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220715', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220715', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220715', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220715', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220715', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220715', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220715', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220715', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220715', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220715', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220715', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220715', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220716', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220716', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220716', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220716', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220716', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220716', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220716', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220716', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220716', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220716', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220716', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220716', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220716', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220716', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220716', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220716', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220716', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220716', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220716', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220716', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220716', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220716', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220716', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220716', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220717', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220717', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220717', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220717', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220717', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220717', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220717', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220717', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220717', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220717', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220717', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220717', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220717', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220717', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220717', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220717', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220717', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220717', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220717', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220717', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220717', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220717', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220717', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220717', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220718', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220718', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220718', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220718', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220718', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220718', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220718', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220718', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220718', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220718', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220718', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220718', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220718', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220718', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220718', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220718', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220718', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220718', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220718', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220718', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220718', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220718', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220718', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220718', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220719', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220719', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220719', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220719', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220719', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220719', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220719', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220719', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220719', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220719', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220719', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220719', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220719', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220719', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220719', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220719', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220719', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220719', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220719', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220719', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220719', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220719', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220719', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220719', 'RR-MM-DD'), 24);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220720', 'RR-MM-DD'), 1);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220720', 'RR-MM-DD'), 2);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220720', 'RR-MM-DD'), 3);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220720', 'RR-MM-DD'), 4);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3122, to_date('220720', 'RR-MM-DD'), 5);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220720', 'RR-MM-DD'), 6);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220720', 'RR-MM-DD'), 7);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220720', 'RR-MM-DD'), 8);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220720', 'RR-MM-DD'), 9);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220720', 'RR-MM-DD'), 10);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220720', 'RR-MM-DD'), 11);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220720', 'RR-MM-DD'), 12);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220720', 'RR-MM-DD'), 13);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3214, to_date('220720', 'RR-MM-DD'), 14);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3112, to_date('220720', 'RR-MM-DD'), 15);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2845, to_date('220720', 'RR-MM-DD'), 16);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220720', 'RR-MM-DD'), 17);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220720', 'RR-MM-DD'), 18);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220720', 'RR-MM-DD'), 19);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3785, to_date('220720', 'RR-MM-DD'), 20);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 2451, to_date('220720', 'RR-MM-DD'), 21);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3512, to_date('220720', 'RR-MM-DD'), 22);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3111, to_date('220720', 'RR-MM-DD'), 23);

INSERT INTO FACTORY (FAC_NO, COUNT, FAC_DATE, ING_NO) 
VALUES (SEQ_FACNO.NEXTVAL, 3089, to_date('220720', 'RR-MM-DD'), 24);

