-- ENROLL : 가맹 신청
INSERT INTO ENROLL
VALUES(SEQ_ENRNO.NEXTVAL,'천성훈','서울시 용산구', 'kojam9041@naver.com',010-2610-6584,'가맹점신청을 원합니다','제목이 곧 내용입니다','B');

-- STORE : 가맹점 개설
INSERT INTO STORE
VALUES('STORE1','GAMENG1','가맹점1','aaa@naver.com','Y',1);

-- SALES테이블 채우기
-- 판매 기입을 할 시, SALES테이블에는 SAL_NO, SAL_DATE가 INSERT
INSERT INTO SALES(SAL_NO, SAL_DATE, COUNT, TOTAL, STORE_ID, MEN_NO)
VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10,
(SELECT PRICE FROM MENU WHERE MEN_NO=1)*10
,'STORE1',1);

		SELECT MEN_NAME, MEN_NO
		FROM MENU;