-- ENROLL : 가맹 신청
INSERT INTO ENROLL
VALUES(SEQ_ENRNO.NEXTVAL,'천성훈','서울시 용산구', 'kojam9041@naver.com',010-2610-6584,'가맹점신청을 원합니다','제목이 곧 내용입니다','B');

-- STORE : 가맹점 개설
INSERT INTO STORE
VALUES('STORE1','GAMENG1','가맹점1','aaa@naver.com','Y',1);

-- SALES테이블 채우기
-- 판매 기입을 할 시, SALES테이블에는 SAL_NO, SAL_DATE가 INSERT
INSERT INTO SALES(SAL_NO, SAL_DATE, COUNT, TOTAL, STORE_ID, MEN_NO)
VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10,
(SELECT PRICE FROM MENU WHERE MEN_NO=1)*10
,'STORE1',1);

SELECT MEN_NAME, MEN_NO
FROM MENU;
  
-- 판매된 제품의 원재료 가져오기
-- SALES테이블에서 판매가 이루어졌을 때, 제품에 대한 원재료를 가져오려고 함.
-- 2022/07/09에 에그마요가 10개가 팔렸다고 가정했을 때,
-- 에그마요에 들어가는 원재료명 : 1,4,5,6,7,11,15,20,22
-- 1번이 10개, 4번이 10개, 5번이 10개, 6번이 10개, 7번이 10개, 11번이 10개, 11번이 10개, 15번이 10개, 20번이 10개, 22번이 10개
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 45000, 'STORE1',1);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 60000, 'STORE1',2);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 55000, 'STORE1',3);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 65000, 'STORE1',4);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 40000, 'STORE1',5);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 45000, 'STORE1',6);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 65000, 'STORE1',7);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 50000, 'STORE1',8);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 55000, 'STORE1',9);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 50000, 'STORE1',10);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 60000, 'STORE1',11);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 60000, 'STORE1',12);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 50000, 'STORE1',13);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 55000, 'STORE1',14);
INSERT INTO SALES VALUES(SEQ_SALESNO.NEXTVAL, SYSDATE, 10, 60000, 'STORE1',15);



SELECT COUNT, SAL_DATE, STORE_ID, ING_NO
FROM SALES S, MENU M, COMBINATION C
WHERE S.MEN_NO = M.MEN_NO
AND M.MEN_NO = C.MEN_NO
AND C.MEN_NO=1
AND S.MEN_NO=1;
       

SELECT COUNT
FROM STOCK
where to_char( 대상 테이블 컬럼, 'yyyymmdd' ) = to_char( sysdate, 'yyyymmdd');

    
        SELECT COUNT(*)
        FROM 
        (
            SELECT STO_DATE, ROW_NUMBER() OVER(PARTITION BY STO_DATE ORDER BY STO_DATE DESC) "RN"
            FROM STOCK S
            JOIN INGREDIENT USING(ING_NO)
            WHERE STORE_ID = 'STORE1'
            AND ING_TYPE= 'B'
            AND ING_NAME= '파마산'
            AND S.STATUS = 'O'
        )
        WHERE RN=1;		

        SELECT TO_CHAR(STO_DATE,'yy.MM.dd'),ING_NAME, COUNT 
        FROM STOCK S
        JOIN INGREDIENT USING(ING_NO)
        WHERE S.STATUS = 'O'
        AND TO_CHAR(STO_DATE,'yy.MM.dd') > TO_CHAR(SYSDATE-14, 'yy.MM.dd')
        AND STORE_ID = 'STORE1'
        AND ING_TYPE= 'S'
        AND ING_NAME= '랜치';


