INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '에그마요'
     , 4500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '로스트치킨'
     , 6000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '쉬림프'
     , 5500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '스테이크치즈'
     , 6500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '베지'
     , 4000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '베지아보카도'
     , 4500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '로스트치킨아보카도'
     , 6500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '비엘티'
     , 5000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '풀드포크바비큐'
     , 5500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '치킨데리야끼'
     , 5000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '터키베이컨아보카도'
     , 6000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '로티세리바비큐치킨'
     , 6000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '이탈리안비엠티'
     , 5000
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , 'K-바비큐'
     , 5500
     , DEFAULT);
INSERT INTO MENU
VALUES(SEQ_MENUNO.NEXTVAL
     , '스파이시이탈리안'
     , 6000
     , DEFAULT);

COMMIT;