-- 시퀀스삭제
DROP SEQUENCE SEQ_ENRNO;
DROP SEQUENCE SEQ_MENUNO;
DROP SEQUENCE SEQ_COMNO;
DROP SEQUENCE SEQ_GNO;
DROP SEQUENCE SEQ_INGNO;
DROP SEQUENCE SEQ_INDENTNO;
DROP SEQUENCE SEQ_STOCKNO;
DROP SEQUENCE SEQ_FLOWNO;
DROP SEQUENCE SEQ_SALESNO;
DROP SEQUENCE SEQ_PAYNO;
DROP SEQUENCE SEQ_INQNO;
DROP SEQUENCE SEQ_FACNO;


--테이블삭제
DROP TABLE COMBINATION; 
DROP TABLE FLOW;
DROP TABLE FACTORY;
DROP TABLE INDENT;
DROP TABLE STOCK;
DROP TABLE SALES;
DROP TABLE PAYMENT;
DROP TABLE INQUERY;
DROP TABLE GREDIENT;
DROP TABLE INGREDIENT;
DROP TABLE STORE;
DROP TABLE ENROLL;
DROP TABLE MENU;

--시퀀스생성
CREATE SEQUENCE SEQ_ENRNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MENUNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_COMNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_INGNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_INDENTNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_STOCKNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_FLOWNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_SALESNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_PAYNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_INQNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_FACNO
START WITH 1
INCREMENT BY 1
MAXVALUE 5000
NOCYCLE
NOCACHE;

-- 테이블 생성
-- 가맹신청 테이블
CREATE TABLE ENROLL(
    ENR_NO NUMBER PRIMARY KEY NOT NULL,                  -- 신청번호   
    STORE_NAME VARCHAR2(15) NOT NULL,                    -- 점주이름 
    ENROLL_ADD VARCHAR2(30) NOT NULL,                    -- 주소
    EMAIL VARCHAR2(200) UNIQUE NOT NULL,                 -- 이메일
    PHONE VARCHAR2(20) NOT NULL,                         -- 전화번호
    TITLE VARCHAR2(150) NOT NULL,                        -- 문의제목
    CONTENT VARCHAR2(300) NOT NULL,                      -- 문의내용
    STATUS VARCHAR2(1) DEFAULT 'B' NOT NULL              -- 상태 (승인 / 반려) 승인시 Y 로 바뀌고, 반려시 N 으로 업데이트
);


-- 가맹신청 COMMENT
COMMENT ON COLUMN ENROLL.ENR_NO IS '신청번호';
COMMENT ON COLUMN ENROLL.STORE_NAME IS '점주이름';
COMMENT ON COLUMN ENROLL.ENROLL_ADD IS '주소';
COMMENT ON COLUMN ENROLL.EMAIL IS '이메일';
COMMENT ON COLUMN ENROLL.PHONE IS '전화번호';
COMMENT ON COLUMN ENROLL.TITLE IS '문의제목';
COMMENT ON COLUMN ENROLL.CONTENT IS '문의내용';
COMMENT ON COLUMN ENROLL.STATUS IS '승인상태';

--가맹점 테이블
CREATE TABLE STORE(
    STORE_ID VARCHAR2(15) PRIMARY KEY NOT NULL,          -- 아이디
    STORE_PWD VARCHAR2(15) NOT NULL,                     -- 비밀번호
    STORE_NAME VARCHAR2(30) UNIQUE NOT NULL,             -- 가맹점명
    ADDRESS VARCHAR2(200) NOT NULL,                      -- 점주이름 
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,             -- 상태 (승인시 Y로 인서트, 폐점처리시 N로 업데이트)
    -- 외래키
    ENR_NO NUMBER NOT NULL,                              -- 가맹번호
    FOREIGN KEY(ENR_NO) REFERENCES ENROLL(ENR_NO) ON DELETE CASCADE  
);

-- 가맹점 COMMENT
COMMENT ON COLUMN STORE.STORE_ID IS '가맹점아이디';
COMMENT ON COLUMN STORE.STORE_PWD IS '가맹점비밀번호';
COMMENT ON COLUMN STORE.STORE_NAME IS '가맹점명';
COMMENT ON COLUMN STORE.ADDRESS IS '점주이름';
COMMENT ON COLUMN STORE.STATUS IS '가맹점상태';
COMMENT ON COLUMN STORE.ENR_NO IS '가맹번호';

-- 원재료 테이블
CREATE TABLE INGREDIENT(
    ING_NO NUMBER PRIMARY KEY NOT NULL,       -- 원재료번호
    ING_NAME VARCHAR2(30) NOT NULL,           -- 원재료명
    PRICE NUMBER NOT NULL,                    -- 원재료 가격
    EXPIRATION NUMBER NOT NULL,               -- 유통기한 
    ING_TYPE VARCHAR2(10) NOT NULL            -- 원재료 종류
);      


-- 원재료 COMMENT
COMMENT ON COLUMN INGREDIENT.ING_NO IS '원재료번호';
COMMENT ON COLUMN INGREDIENT.ING_NAME IS '원재료명';
COMMENT ON COLUMN INGREDIENT.PRICE IS '원재료가격';
COMMENT ON COLUMN INGREDIENT.EXPIRATION IS '유통기한';
COMMENT ON COLUMN INGREDIENT.ING_TYPE IS '원재료종류';


-- 메뉴 테이블
CREATE TABLE MENU(
    MEN_NO NUMBER PRIMARY KEY NOT NULL,          -- 메뉴번호
    MEN_NAME VARCHAR2(50) NOT NULL,              -- 메뉴이름 
    PRICE NUMBER NOT NULL,                       -- 메뉴가격
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL      -- 상태(판매여부)
);

-- 메뉴 COMMENT
COMMENT ON COLUMN MENU.MEN_NO IS '메뉴번호';
COMMENT ON COLUMN MENU.MEN_NAME IS '메뉴이름';
COMMENT ON COLUMN MENU.PRICE IS '메뉴가격';
COMMENT ON COLUMN MENU.STATUS IS '메뉴상태(판매여부)';

-- 조합 테이블
CREATE TABLE COMBINATION(
    COM_NO NUMBER PRIMARY KEY NOT NULL,                     -- 조합 번호
    -- 외래키
    MEN_NO NUMBER NOT NULL,                                 -- 메뉴번호
    FOREIGN KEY (MEN_NO) REFERENCES MENU(MEN_NO) ON DELETE CASCADE, 
    ING_NO NUMBER NOT NULL,                                 -- 원재료번호
    FOREIGN KEY (ING_NO) REFERENCES INGREDIENT(ING_NO) ON DELETE CASCADE
);

-- 메뉴조합 COMMENT
COMMENT ON COLUMN COMBINATION.COM_NO IS '조합번호';
COMMENT ON COLUMN COMBINATION.MEN_NO IS '메뉴번호';
COMMENT ON COLUMN COMBINATION.ING_NO IS '원재료번호';

-- 발주 테이블
CREATE TABLE INDENT(
    IND_NO NUMBER PRIMARY KEY NOT NULL,                     --발주번호
    COUNT NUMBER  NOT NULL,                                 --발주갯수
    IND_DATE DATE DEFAULT SYSDATE NOT NULL,                 --발주날짜
    TOTAL NUMBER NOT NULL,                                  --발주총가격
    STATUS VARCHAR2(5) DEFAULT 'B' NOT NULL,                --발주상태(B > Y or N, AB > AY or N)
    STORE_ID VARCHAR2(15) NOT NULL,                                  --가맹점아이디
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID) ON DELETE CASCADE,
    ING_NO NUMBER NOT NULL,                                          --원재료번호
    FOREIGN KEY (ING_NO) REFERENCES INGREDIENT(ING_NO) ON DELETE CASCADE
);

-- 발주 COMMENT
COMMENT ON COLUMN INDENT.IND_NO IS '발주번호';
COMMENT ON COLUMN INDENT.COUNT IS '발주갯수';
COMMENT ON COLUMN INDENT.IND_DATE IS '발주날짜';
COMMENT ON COLUMN INDENT.TOTAL IS '발주총가격';
COMMENT ON COLUMN INDENT.STATUS IS '발주상태';
COMMENT ON COLUMN INDENT.STORE_ID IS '가맹점아이디';
COMMENT ON COLUMN INDENT.ING_NO IS '원재료번호';

-- 재고 테이블
CREATE TABLE STOCK (
    STO_NO NUMBER PRIMARY KEY NOT NULL,                 --재고번호
    STO_DATE DATE DEFAULT SYSDATE NOT NULL,             --입고날짜
    COUNT NUMBER NOT NULL,                              --재고갯수
    STATUS VARCHAR2(1) DEFAULT 'O' NOT NULL ,           --재고상태
    -- 외래키
    STORE_ID VARCHAR2(15) NOT NULL,                     --가맹점아이디
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID) ON DELETE CASCADE,
    ING_NO NUMBER NOT NULL,                             --원재료번호
    FOREIGN KEY (ING_NO) REFERENCES INGREDIENT(ING_NO) ON DELETE CASCADE
);

-- 재고 COMMENT
COMMENT ON COLUMN STOCK.STO_NO IS '재고번호';
COMMENT ON COLUMN STOCK.STO_DATE IS '입고날짜';
COMMENT ON COLUMN STOCK.COUNT IS '재고갯수';
COMMENT ON COLUMN STOCK.STATUS IS '재고상태';
COMMENT ON COLUMN STOCK.STORE_ID IS '가맹점아이디';
COMMENT ON COLUMN STOCK.ING_NO IS '원재료번호';


-- 원재료 입출고내역 테이블
CREATE TABLE FLOW(
    FLO_NO NUMBER NOT NULL,                     --입출고번호
    COUNT NUMBER NOT NULL,                      --입출고갯수
    FLO_DATE DATE DEFAULT SYSDATE NOT NULL,     --입출고날짜
    STATUS VARCHAR2(1) NOT NULL, -- I O         --입출고상태
    -- 외래키
    STORE_ID VARCHAR2(15) NOT NULL,             --가맹점아이디
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID) ON DELETE CASCADE,
    ING_NO NUMBER NOT NULL,                     --원재료번호
    FOREIGN KEY (ING_NO) REFERENCES INGREDIENT(ING_NO)ON DELETE CASCADE 
);  

-- 원재료 입출고내역 COMMENT
COMMENT ON COLUMN FLOW.FLO_NO IS '입출고번호';
COMMENT ON COLUMN FLOW.COUNT IS '입출고갯수';
COMMENT ON COLUMN FLOW.FLO_DATE IS '입출고날짜';
COMMENT ON COLUMN FLOW.STATUS IS '입출고상태';
COMMENT ON COLUMN FLOW.STORE_ID IS '가맹점아이디';
COMMENT ON COLUMN FLOW.ING_NO IS '원재료번호';

-- 공장 자동발주내역 테이블
CREATE TABLE FACTORY(
    FAC_NO NUMBER NOT NULL,                     --공장발주번호
    COUNT NUMBER NOT NULL,                      --공장발주갯수
    FAC_DATE DATE DEFAULT SYSDATE NOT NULL,     --공장발주날짜
    -- 외래키
    ING_NO NUMBER NOT NULL,                     --원재료번호
    FOREIGN KEY (ING_NO) REFERENCES INGREDIENT(ING_NO)ON DELETE CASCADE 
);  

-- 공장 자동발주내역 테이블 COMMENT
COMMENT ON COLUMN FACTORY.FAC_NO IS '공장발주번호';
COMMENT ON COLUMN FACTORY.COUNT IS '공장발주갯수';
COMMENT ON COLUMN FACTORY.FAC_DATE IS '공장발주날짜';
COMMENT ON COLUMN FACTORY.ING_NO IS '원재료번호';

--판매(매출) 테이블
CREATE TABLE SALES (
    SAL_NO NUMBER NOT NULL PRIMARY KEY,         --판매번호
    SAL_DATE DATE DEFAULT SYSDATE NOT NULL,     --판매날짜
    COUNT NUMBER NOT NULL,                      --판매갯수
    TOTAL NUMBER NOT NULL,                      --총판매액
    -- 외래키
    STORE_ID VARCHAR2(15) NOT NULL,             --가맹점아이디
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID) ON DELETE CASCADE,
    MEN_NO NUMBER NOT NULL,                     --메뉴번호
    FOREIGN KEY (MEN_NO) REFERENCES MENU(MEN_NO)
);

-- 판매(매출) COMMENT
COMMENT ON COLUMN SALES.SAL_NO IS '판매(매출)번호';
COMMENT ON COLUMN SALES.SAL_DATE IS '판매(매출)날짜';
COMMENT ON COLUMN SALES.COUNT IS '판매(매출)갯수';
COMMENT ON COLUMN SALES.TOTAL IS '총판매(매출)액';
COMMENT ON COLUMN SALES.STORE_ID IS '가맹점아이디';
COMMENT ON COLUMN SALES.MEN_NO IS '메뉴번호';

-- 입금 테이블
CREATE TABLE PAYMENT(
    PAY_NO NUMBER PRIMARY KEY NOT NULL,         --입금번호
    DEPOSIT NUMBER NOT NULL,                    --입금액
    WITHDRAW NUMBER NOT NULL,                   --출금액
    PAY_DATE DATE NOT NULL,                     --입금날짜
    -- 외래키
    STORE_ID VARCHAR2(15) NOT NULL,             --가맹점아이디
    FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID)
);

-- 입금 COMMENT
COMMENT ON COLUMN PAYMENT.PAY_NO IS '입금번호';
COMMENT ON COLUMN PAYMENT.DEPOSIT IS '입금액';
COMMENT ON COLUMN PAYMENT.WITHDRAW IS '출금액';
COMMENT ON COLUMN PAYMENT.PAY_DATE IS '입금날짜';
COMMENT ON COLUMN PAYMENT.STORE_ID IS '가맹점아이디';

-- 문의 테이블
CREATE TABLE INQUERY(
    INQ_NO NUMBER NOT NULL,                     --문의번호
    INQ_TITLE VARCHAR2(150) NOT NULL,           --문의제목
    INQ_DATE DATE DEFAULT SYSDATE NOT NULL,     --문의날짜
    INQ_QUERY VARCHAR2(3000) NOT NULL,          --문의내용
    INQ_ANSWER VARCHAR2(3000),                  --문의답변
    STATUS VARCHAR2(1) DEFAULT 'N'  NOT NULL,                --문의상태
    ANS_DATE DATE,                               --답변날짜
    CATEGORY VARCHAR2(30) NOT NULL,             --문의카테고리
    -- 외래키
    STORE_ID VARCHAR2(15) NOT NULL,             --가맹점아이디
    FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID) 
);

-- 문의 COMMENT
COMMENT ON COLUMN INQUERY.INQ_NO IS '문의번호';
COMMENT ON COLUMN INQUERY.INQ_TITLE IS '문의제목';
COMMENT ON COLUMN INQUERY.INQ_DATE IS '문의날짜';
COMMENT ON COLUMN INQUERY.INQ_QUERY IS '문의내용';
COMMENT ON COLUMN INQUERY.INQ_ANSWER IS '문의답변';
COMMENT ON COLUMN INQUERY.STATUS IS '문의글상태';
COMMENT ON COLUMN INQUERY.ANS_DATE IS '답변날짜';
COMMENT ON COLUMN INQUERY.CATEGORY IS '문의카테고리';
COMMENT ON COLUMN INQUERY.STORE_ID IS '가맹점아이디';

COMMIT;




